# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt update
    sudo apt install make systemd-coredump
    sudo ulimit -c unlimited
    make
    ./main
  displayName: make and run
- script: |
    coredumpctl list
    coredumpctl info
  condition: Failed()
  displayName: 'failed'

